set(RESOURCES
Main.storyboard
./assets/default/raw/ui/label.bin
./assets/default/raw/ui/menu_left_bottom.bin
./assets/default/raw/ui/image_value.bin
./assets/default/raw/ui/system_bar_bottom.bin
./assets/default/raw/ui/system_bar.bin
./assets/default/raw/ui/slide_up.bin
./assets/default/raw/ui/auto_play_landscape.bin
./assets/default/raw/ui/auto_play_portrait.bin
./assets/default/raw/ui/draggable.bin
./assets/default/raw/ui/kb_ufloat.bin
./assets/default/raw/ui/animation.bin
./assets/default/raw/ui/tab_scrollable.bin
./assets/default/raw/ui/menu_up_center.bin
./assets/default/raw/ui/menu_right_bottom.bin
./assets/default/raw/ui/list_view.bin
./assets/default/raw/ui/tab_bottom_compact.bin
./assets/default/raw/ui/kb_default.bin
./assets/default/raw/ui/menu_point.bin
./assets/default/raw/ui/kb_int.bin
./assets/default/raw/ui/popdown.bin
./assets/default/raw/ui/tab_button_view_page2.bin
./assets/default/raw/ui/scroll_view_h.bin
./assets/default/raw/ui/slide_down.bin
./assets/default/raw/ui/hscroll_label.bin
./assets/default/raw/ui/tab_list.bin
./assets/default/raw/ui/kb_ascii.bin
./assets/default/raw/ui/guage.bin
./assets/default/raw/ui/image_animation.bin
./assets/default/raw/ui/slide_view_h.bin
./assets/default/raw/ui/kb_phone.bin
./assets/default/raw/ui/auto_play.bin
./assets/default/raw/ui/tab_button_view_page1.bin
./assets/default/raw/ui/animator.bin
./assets/default/raw/ui/memtest.bin
./assets/default/raw/ui/scroll_view.bin
./assets/default/raw/ui/list_view_m.bin
./assets/default/raw/ui/lua.bin
./assets/default/raw/ui/tab_top_compact.bin
./assets/default/raw/ui/mledit.bin
./assets/default/raw/ui/file_browser.bin
./assets/default/raw/ui/fade.bin
./assets/default/raw/ui/scroll_bar_h.bin
./assets/default/raw/ui/tab_dynamic_list.bin
./assets/default/raw/ui/menu_down_center.bin
./assets/default/raw/ui/vtranslate.bin
./assets/default/raw/ui/calibration_win.bin
./assets/default/raw/ui/digit_clock.bin
./assets/default/raw/ui/menu_right_top.bin
./assets/default/raw/ui/text_selector.bin
./assets/default/raw/ui/tab_bottom.bin
./assets/default/raw/ui/list_view_vh.bin
./assets/default/raw/ui/selectm.bin
./assets/default/raw/ui/slide_right.bin
./assets/default/raw/ui/color_picker_full.bin
./assets/default/raw/ui/htranslate.bin
./assets/default/raw/ui/rich_text1.bin
./assets/default/raw/ui/test_view.bin
./assets/default/raw/ui/list_view_h.bin
./assets/default/raw/ui/mono_test.bin
./assets/default/raw/ui/keyboard.bin
./assets/default/raw/ui/menu_down_left.bin
./assets/default/raw/ui/rich_text2.bin
./assets/default/raw/ui/main.bin
./assets/default/raw/ui/list_view_d.bin
./assets/default/raw/ui/tab_control.bin
./assets/default/raw/ui/menu_up_right.bin
./assets/default/raw/ui/edit.bin
./assets/default/raw/ui/overlay.bin
./assets/default/raw/ui/menu_left_top.bin
./assets/default/raw/ui/gif_image.bin
./assets/default/raw/ui/vgcanvas.bin
./assets/default/raw/ui/menu_right_middle.bin
./assets/default/raw/ui/soft_keyboard.bin
./assets/default/raw/ui/slide_view_h1.bin
./assets/default/raw/ui/locale.bin
./assets/default/raw/ui/svg_image.bin
./assets/default/raw/ui/basic.bin
./assets/default/raw/ui/linear_gradient.bin
./assets/default/raw/ui/rich_text.bin
./assets/default/raw/ui/color_picker.bin
./assets/default/raw/ui/combo_box.bin
./assets/default/raw/ui/menu_left_middle.bin
./assets/default/raw/ui/slide_view_h2.bin
./assets/default/raw/ui/color_picker_rgb.bin
./assets/default/raw/ui/button.bin
./assets/default/raw/ui/select1.bin
./assets/default/raw/ui/image_list.bin
./assets/default/raw/ui/progress_circle.bin
./assets/default/raw/ui/images.bin
./assets/default/raw/ui/back_to_home.bin
./assets/default/raw/ui/stroke_gradient.bin
./assets/default/raw/ui/file_chooser_for_save.bin
./assets/default/raw/ui/slide_view_v2.bin
./assets/default/raw/ui/kb_float.bin
./assets/default/raw/ui/big_font.bin
./assets/default/raw/ui/popup.bin
./assets/default/raw/ui/color_picker_hsv.bin
./assets/default/raw/ui/scroll_bar.bin
./assets/default/raw/ui/slide_view.bin
./assets/default/raw/ui/slide_view_h_loop.bin
./assets/default/raw/ui/dialog1.bin
./assets/default/raw/ui/slide_view_v1.bin
./assets/default/raw/ui/menu_down_right.bin
./assets/default/raw/ui/menu.bin
./assets/default/raw/ui/dialog2.bin
./assets/default/raw/ui/dialogs.bin
./assets/default/raw/ui/switch.bin
./assets/default/raw/ui/preload.bin
./assets/default/raw/ui/tab_top.bin
./assets/default/raw/ui/color.bin
./assets/default/raw/ui/color_picker_simple.bin
./assets/default/raw/ui/spinbox.bin
./assets/default/raw/ui/radial_gradient.bin
./assets/default/raw/ui/slide_left.bin
./assets/default/raw/ui/scroll_view_v.bin
./assets/default/raw/ui/slide_view_v_loop.bin
./assets/default/raw/ui/kb_uint.bin
./assets/default/raw/ui/time_clock.bin
./assets/default/raw/ui/kb_hex.bin
./assets/default/raw/ui/menu_up_left.bin
./assets/default/raw/ui/slide_menu.bin
./assets/default/raw/ui/dragger.bin
./assets/default/raw/ui/language.bin
./assets/default/raw/ui/file_chooser_for_open.bin
./assets/default/raw/ui/slide_view_v.bin
./assets/default/raw/ui/mutable_image.bin
./assets/default/raw/ui/folder_chooser.bin
./assets/default/raw/strings/zh_CN.bin
./assets/default/raw/strings/en_US.bin
./assets/default/raw/styles/system_bar_bottom.bin
./assets/default/raw/styles/system_bar.bin
./assets/default/raw/styles/dialog_confirm.bin
./assets/default/raw/styles/tab_bottom_compact.bin
./assets/default/raw/styles/dialog_info.bin
./assets/default/raw/styles/tab_list.bin
./assets/default/raw/styles/guage.bin
./assets/default/raw/styles/tab_top_compact.bin
./assets/default/raw/styles/file_browser.bin
./assets/default/raw/styles/digit_clock.bin
./assets/default/raw/styles/tab_bottom.bin
./assets/default/raw/styles/keyboard.bin
./assets/default/raw/styles/edit.bin
./assets/default/raw/styles/default.bin
./assets/default/raw/styles/button.bin
./assets/default/raw/styles/calibration.bin
./assets/default/raw/styles/big_font.bin
./assets/default/raw/styles/dialog.bin
./assets/default/raw/styles/dialog_toast.bin
./assets/default/raw/styles/tab_top.bin
./assets/default/raw/styles/dialog_warn.bin
./assets/default/raw/styles/color.bin
./assets/default/raw/styles/slide_menu.bin
./assets/default/raw/images/x1/info.png
./assets/default/raw/images/x1/me.png
./assets/default/raw/images/x1/middle_off.png
./assets/default/raw/images/x1/red_btn_p.png
./assets/default/raw/images/x1/check.png
./assets/default/raw/images/x1/cursor.png
./assets/default/raw/images/x1/green_btn_n.png
./assets/default/raw/images/x1/muted.png
./assets/default/raw/images/x1/arrow_down_o.png
./assets/default/raw/images/x1/rgb.png
./assets/default/raw/images/x1/arrow_down_n.png
./assets/default/raw/images/x1/green_btn_o.png
./assets/default/raw/images/x1/return_up.png
./assets/default/raw/images/x1/msg_active.png
./assets/default/raw/images/x1/play_n.png
./assets/default/raw/images/x1/radio_checked.png
./assets/default/raw/images/x1/middle_on.png
./assets/default/raw/images/x1/msg.png
./assets/default/raw/images/x1/play_o.png
./assets/default/raw/images/x1/bricks.png
./assets/default/raw/images/x1/shifton.png
./assets/default/raw/images/x1/active_dot.png
./assets/default/raw/images/x1/question.png
./assets/default/raw/images/x1/zh.png
./assets/default/raw/images/x1/discovery_active.png
./assets/default/raw/images/x1/dot.png
./assets/default/raw/images/x1/rgba.png
./assets/default/raw/images/x1/empty.png
./assets/default/raw/images/x1/battery_0.png
./assets/default/raw/images/x1/slider_v_fg.png
./assets/default/raw/images/x1/ani1.png
./assets/default/raw/images/x1/visible.png
./assets/default/raw/images/x1/edit_clear_p.png
./assets/default/raw/images/x1/arrow_up_o.png
./assets/default/raw/images/x1/arrow_up_n.png
./assets/default/raw/images/x1/left_on.png
./assets/default/raw/images/x1/file.png
./assets/default/raw/images/x1/battery_1.png
./assets/default/raw/images/x1/arrow_right_p.png
./assets/default/raw/images/x1/battery_3.png
./assets/default/raw/images/x1/slider_drag_o.png
./assets/default/raw/images/x1/en.png
./assets/default/raw/images/x1/ani2.png
./assets/default/raw/images/x1/arrow_left_n.png
./assets/default/raw/images/x1/clock_second.png
./assets/default/raw/images/x1/arrow_left_o.png
./assets/default/raw/images/x1/ani3.png
./assets/default/raw/images/x1/battery_2.png
./assets/default/raw/images/x1/ania.png
./assets/default/raw/images/x1/ani7.png
./assets/default/raw/images/x1/shift.png
./assets/default/raw/images/x1/ani6.png
./assets/default/raw/images/x1/close_p.png
./assets/default/raw/images/x1/checked.png
./assets/default/raw/images/x1/battery_5.png
./assets/default/raw/images/x1/anib.png
./assets/default/raw/images/x1/ani4.png
./assets/default/raw/images/x1/me_active.png
./assets/default/raw/images/x1/ani5.png
./assets/default/raw/images/x1/anic.png
./assets/default/raw/images/x1/earth.png
./assets/default/raw/images/x1/contact_active.png
./assets/default/raw/images/x1/dialog_title.png
./assets/default/raw/images/x1/close_d.png
./assets/default/raw/images/x1/battery_4.png
./assets/default/raw/images/x1/contact.png
./assets/default/raw/images/x1/slider_fg.png
./assets/default/raw/images/x1/arrow_right_o.png
./assets/default/raw/images/x1/ani8.png
./assets/default/raw/images/x1/edit_clear_n.png
./assets/default/raw/images/x1/arrow_up_p.png
./assets/default/raw/images/x1/edit_clear_o.png
./assets/default/raw/images/x1/folder.png
./assets/default/raw/images/x1/ani9.png
./assets/default/raw/images/x1/find.png
./assets/default/raw/images/x1/discovery.png
./assets/default/raw/images/x1/arrow_right_n.png
./assets/default/raw/images/x1/backspace.png
./assets/default/raw/images/x1/arrow_left_p.png
./assets/default/raw/images/x1/clock_hour.png
./assets/default/raw/images/x1/slider_drag_p.png
./assets/default/raw/images/x1/logo.png
./assets/default/raw/images/x1/invisible.png
./assets/default/raw/images/x1/close_o.png
./assets/default/raw/images/x1/cross.png
./assets/default/raw/images/x1/clock_minute.png
./assets/default/raw/images/x1/radio_unchecked.png
./assets/default/raw/images/x1/switch.png
./assets/default/raw/images/x1/close_n.png
./assets/default/raw/images/x1/clock.png
./assets/default/raw/images/x1/unchecked.png
./assets/default/raw/images/x1/red_btn_n.png
./assets/default/raw/images/x1/slider_drag.png
./assets/default/raw/images/x1/red_btn_o.png
./assets/default/raw/images/x1/green_btn_p.png
./assets/default/raw/images/x1/arrow_down_p.png
./assets/default/raw/images/x1/warn.png
./assets/default/raw/images/x1/slider_v_bg.png
./assets/default/raw/images/x1/right_on.png
./assets/default/raw/images/x1/slider_bg.png
./assets/default/raw/images/x1/guage_pointer.png
./assets/default/raw/images/x1/play_p.png
./assets/default/raw/images/x1/unmuted.png
./assets/default/raw/images/x1/right_off.png
./assets/default/raw/images/x1/message.png
./assets/default/raw/images/x1/progress_circle.png
./assets/default/raw/images/x1/left_off.png
./assets/default/raw/images/xx/flag_CN.png
./assets/default/raw/images/xx/flag_US.png
./assets/default/raw/images/x3/info.png
./assets/default/raw/images/x3/me.png
./assets/default/raw/images/x3/middle_off.png
./assets/default/raw/images/x3/red_btn_p.png
./assets/default/raw/images/x3/check.png
./assets/default/raw/images/x3/cursor.png
./assets/default/raw/images/x3/green_btn_n.png
./assets/default/raw/images/x3/muted.png
./assets/default/raw/images/x3/arrow_down_o.png
./assets/default/raw/images/x3/rgb.png
./assets/default/raw/images/x3/arrow_down_n.png
./assets/default/raw/images/x3/green_btn_o.png
./assets/default/raw/images/x3/msg_active.png
./assets/default/raw/images/x3/play_n.png
./assets/default/raw/images/x3/radio_checked.png
./assets/default/raw/images/x3/middle_on.png
./assets/default/raw/images/x3/msg.png
./assets/default/raw/images/x3/play_o.png
./assets/default/raw/images/x3/bricks.png
./assets/default/raw/images/x3/shifton.png
./assets/default/raw/images/x3/active_dot.png
./assets/default/raw/images/x3/question.png
./assets/default/raw/images/x3/zh.png
./assets/default/raw/images/x3/discovery_active.png
./assets/default/raw/images/x3/dot.png
./assets/default/raw/images/x3/rgba.png
./assets/default/raw/images/x3/empty.png
./assets/default/raw/images/x3/battery_0.png
./assets/default/raw/images/x3/slider_v_fg.png
./assets/default/raw/images/x3/ani1.png
./assets/default/raw/images/x3/visible.png
./assets/default/raw/images/x3/edit_clear_p.png
./assets/default/raw/images/x3/arrow_up_o.png
./assets/default/raw/images/x3/arrow_up_n.png
./assets/default/raw/images/x3/left_on.png
./assets/default/raw/images/x3/battery_1.png
./assets/default/raw/images/x3/arrow_right_p.png
./assets/default/raw/images/x3/guage_bg.png
./assets/default/raw/images/x3/battery_3.png
./assets/default/raw/images/x3/slider_drag_o.png
./assets/default/raw/images/x3/en.png
./assets/default/raw/images/x3/ani2.png
./assets/default/raw/images/x3/arrow_left_n.png
./assets/default/raw/images/x3/clock_second.png
./assets/default/raw/images/x3/arrow_left_o.png
./assets/default/raw/images/x3/ani3.png
./assets/default/raw/images/x3/battery_2.png
./assets/default/raw/images/x3/ania.png
./assets/default/raw/images/x3/ani7.png
./assets/default/raw/images/x3/shift.png
./assets/default/raw/images/x3/ani6.png
./assets/default/raw/images/x3/close_p.png
./assets/default/raw/images/x3/checked.png
./assets/default/raw/images/x3/battery_5.png
./assets/default/raw/images/x3/anib.png
./assets/default/raw/images/x3/ani4.png
./assets/default/raw/images/x3/me_active.png
./assets/default/raw/images/x3/ani5.png
./assets/default/raw/images/x3/anic.png
./assets/default/raw/images/x3/earth.png
./assets/default/raw/images/x3/contact_active.png
./assets/default/raw/images/x3/dialog_title.png
./assets/default/raw/images/x3/close_d.png
./assets/default/raw/images/x3/battery_4.png
./assets/default/raw/images/x3/contact.png
./assets/default/raw/images/x3/slider_fg.png
./assets/default/raw/images/x3/arrow_right_o.png
./assets/default/raw/images/x3/ani8.png
./assets/default/raw/images/x3/edit_clear_n.png
./assets/default/raw/images/x3/arrow_up_p.png
./assets/default/raw/images/x3/edit_clear_o.png
./assets/default/raw/images/x3/ani9.png
./assets/default/raw/images/x3/find.png
./assets/default/raw/images/x3/discovery.png
./assets/default/raw/images/x3/arrow_right_n.png
./assets/default/raw/images/x3/backspace.png
./assets/default/raw/images/x3/arrow_left_p.png
./assets/default/raw/images/x3/clock_hour.png
./assets/default/raw/images/x3/slider_drag_p.png
./assets/default/raw/images/x3/logo.png
./assets/default/raw/images/x3/invisible.png
./assets/default/raw/images/x3/close_o.png
./assets/default/raw/images/x3/cross.png
./assets/default/raw/images/x3/clock_minute.png
./assets/default/raw/images/x3/radio_unchecked.png
./assets/default/raw/images/x3/switch.png
./assets/default/raw/images/x3/close_n.png
./assets/default/raw/images/x3/clock.png
./assets/default/raw/images/x3/unchecked.png
./assets/default/raw/images/x3/red_btn_n.png
./assets/default/raw/images/x3/slider_drag.png
./assets/default/raw/images/x3/red_btn_o.png
./assets/default/raw/images/x3/green_btn_p.png
./assets/default/raw/images/x3/arrow_down_p.png
./assets/default/raw/images/x3/warn.png
./assets/default/raw/images/x3/slider_v_bg.png
./assets/default/raw/images/x3/right_on.png
./assets/default/raw/images/x3/slider_bg.png
./assets/default/raw/images/x3/guage_pointer.png
./assets/default/raw/images/x3/play_p.png
./assets/default/raw/images/x3/unmuted.png
./assets/default/raw/images/x3/right_off.png
./assets/default/raw/images/x3/message.png
./assets/default/raw/images/x3/progress_circle.png
./assets/default/raw/images/x3/left_off.png
./assets/default/raw/images/x2/info.png
./assets/default/raw/images/x2/me.png
./assets/default/raw/images/x2/middle_off.png
./assets/default/raw/images/x2/red_btn_p.png
./assets/default/raw/images/x2/check.png
./assets/default/raw/images/x2/cursor.png
./assets/default/raw/images/x2/green_btn_n.png
./assets/default/raw/images/x2/muted.png
./assets/default/raw/images/x2/arrow_down_o.png
./assets/default/raw/images/x2/rgb.png
./assets/default/raw/images/x2/arrow_down_n.png
./assets/default/raw/images/x2/green_btn_o.png
./assets/default/raw/images/x2/return_up.png
./assets/default/raw/images/x2/msg_active.png
./assets/default/raw/images/x2/play_n.png
./assets/default/raw/images/x2/radio_checked.png
./assets/default/raw/images/x2/middle_on.png
./assets/default/raw/images/x2/msg.png
./assets/default/raw/images/x2/play_o.png
./assets/default/raw/images/x2/bricks.png
./assets/default/raw/images/x2/shifton.png
./assets/default/raw/images/x2/active_dot.png
./assets/default/raw/images/x2/question.png
./assets/default/raw/images/x2/zh.png
./assets/default/raw/images/x2/discovery_active.png
./assets/default/raw/images/x2/dot.png
./assets/default/raw/images/x2/rgba.png
./assets/default/raw/images/x2/empty.png
./assets/default/raw/images/x2/battery_0.png
./assets/default/raw/images/x2/slider_v_fg.png
./assets/default/raw/images/x2/ani1.png
./assets/default/raw/images/x2/visible.png
./assets/default/raw/images/x2/edit_clear_p.png
./assets/default/raw/images/x2/arrow_up_o.png
./assets/default/raw/images/x2/arrow_up_n.png
./assets/default/raw/images/x2/left_on.png
./assets/default/raw/images/x2/file.png
./assets/default/raw/images/x2/battery_1.png
./assets/default/raw/images/x2/arrow_right_p.png
./assets/default/raw/images/x2/guage_bg.png
./assets/default/raw/images/x2/battery_3.png
./assets/default/raw/images/x2/slider_drag_o.png
./assets/default/raw/images/x2/en.png
./assets/default/raw/images/x2/ani2.png
./assets/default/raw/images/x2/arrow_left_n.png
./assets/default/raw/images/x2/clock_second.png
./assets/default/raw/images/x2/arrow_left_o.png
./assets/default/raw/images/x2/ani3.png
./assets/default/raw/images/x2/battery_2.png
./assets/default/raw/images/x2/ania.png
./assets/default/raw/images/x2/ani7.png
./assets/default/raw/images/x2/shift.png
./assets/default/raw/images/x2/ani6.png
./assets/default/raw/images/x2/close_p.png
./assets/default/raw/images/x2/checked.png
./assets/default/raw/images/x2/battery_5.png
./assets/default/raw/images/x2/anib.png
./assets/default/raw/images/x2/ani4.png
./assets/default/raw/images/x2/me_active.png
./assets/default/raw/images/x2/ani5.png
./assets/default/raw/images/x2/anic.png
./assets/default/raw/images/x2/earth.png
./assets/default/raw/images/x2/contact_active.png
./assets/default/raw/images/x2/dialog_title.png
./assets/default/raw/images/x2/close_d.png
./assets/default/raw/images/x2/battery_4.png
./assets/default/raw/images/x2/contact.png
./assets/default/raw/images/x2/slider_fg.png
./assets/default/raw/images/x2/arrow_right_o.png
./assets/default/raw/images/x2/ani8.png
./assets/default/raw/images/x2/edit_clear_n.png
./assets/default/raw/images/x2/arrow_up_p.png
./assets/default/raw/images/x2/edit_clear_o.png
./assets/default/raw/images/x2/folder.png
./assets/default/raw/images/x2/ani9.png
./assets/default/raw/images/x2/find.png
./assets/default/raw/images/x2/discovery.png
./assets/default/raw/images/x2/arrow_right_n.png
./assets/default/raw/images/x2/backspace.png
./assets/default/raw/images/x2/arrow_left_p.png
./assets/default/raw/images/x2/clock_hour.png
./assets/default/raw/images/x2/slider_drag_p.png
./assets/default/raw/images/x2/logo.png
./assets/default/raw/images/x2/invisible.png
./assets/default/raw/images/x2/close_o.png
./assets/default/raw/images/x2/cross.png
./assets/default/raw/images/x2/clock_minute.png
./assets/default/raw/images/x2/radio_unchecked.png
./assets/default/raw/images/x2/switch.png
./assets/default/raw/images/x2/close_n.png
./assets/default/raw/images/x2/clock.png
./assets/default/raw/images/x2/unchecked.png
./assets/default/raw/images/x2/red_btn_n.png
./assets/default/raw/images/x2/slider_drag.png
./assets/default/raw/images/x2/red_btn_o.png
./assets/default/raw/images/x2/green_btn_p.png
./assets/default/raw/images/x2/arrow_down_p.png
./assets/default/raw/images/x2/warn.png
./assets/default/raw/images/x2/slider_v_bg.png
./assets/default/raw/images/x2/right_on.png
./assets/default/raw/images/x2/slider_bg.png
./assets/default/raw/images/x2/guage_pointer.png
./assets/default/raw/images/x2/play_p.png
./assets/default/raw/images/x2/unmuted.png
./assets/default/raw/images/x2/right_off.png
./assets/default/raw/images/x2/message.png
./assets/default/raw/images/x2/progress_circle.png
./assets/default/raw/images/x2/left_off.png
./assets/default/raw/images/x1/num_dot.jpg
./assets/default/raw/images/x1/num_0.jpg
./assets/default/raw/images/x1/num_1.jpg
./assets/default/raw/images/x1/num_3.jpg
./assets/default/raw/images/x1/guage_bg.jpg
./assets/default/raw/images/x1/num_2.jpg
./assets/default/raw/images/x1/num_6.jpg
./assets/default/raw/images/x1/num_7.jpg
./assets/default/raw/images/x1/num_5.jpg
./assets/default/raw/images/x1/num_4.jpg
./assets/default/raw/images/x1/num_9.jpg
./assets/default/raw/images/x1/num_8.jpg
./assets/default/raw/images/x1/clock_bg.jpg
./assets/default/raw/images/x1/2.jpg
./assets/default/raw/images/x1/3.jpg
./assets/default/raw/images/x1/1.jpg
./assets/default/raw/images/xx/bg_landscape_1.jpg
./assets/default/raw/images/xx/bg_landscape_2.jpg
./assets/default/raw/images/xx/flag_none.jpg
./assets/default/raw/images/xx/bg_landscape_3.jpg
./assets/default/raw/images/xx/bg_portrait_1.jpg
./assets/default/raw/images/xx/bg_portrait_2.jpg
./assets/default/raw/images/xx/bg_portrait_3.jpg
./assets/default/raw/images/x3/num_dot.jpg
./assets/default/raw/images/x3/num_0.jpg
./assets/default/raw/images/x3/num_1.jpg
./assets/default/raw/images/x3/num_3.jpg
./assets/default/raw/images/x3/num_2.jpg
./assets/default/raw/images/x3/num_6.jpg
./assets/default/raw/images/x3/num_7.jpg
./assets/default/raw/images/x3/num_5.jpg
./assets/default/raw/images/x3/num_4.jpg
./assets/default/raw/images/x3/num_9.jpg
./assets/default/raw/images/x3/num_8.jpg
./assets/default/raw/images/x3/clock_bg.jpg
./assets/default/raw/images/x3/2.jpg
./assets/default/raw/images/x3/3.jpg
./assets/default/raw/images/x3/1.jpg
./assets/default/raw/images/x2/num_dot.jpg
./assets/default/raw/images/x2/num_0.jpg
./assets/default/raw/images/x2/num_1.jpg
./assets/default/raw/images/x2/num_3.jpg
./assets/default/raw/images/x2/num_2.jpg
./assets/default/raw/images/x2/num_6.jpg
./assets/default/raw/images/x2/num_7.jpg
./assets/default/raw/images/x2/num_5.jpg
./assets/default/raw/images/x2/num_4.jpg
./assets/default/raw/images/x2/num_9.jpg
./assets/default/raw/images/x2/num_8.jpg
./assets/default/raw/images/x2/clock_bg.jpg
./assets/default/raw/images/x2/2.jpg
./assets/default/raw/images/x2/3.jpg
./assets/default/raw/images/x2/1.jpg
./assets/default/raw/fonts/default.ttf
./assets/default/raw/fonts/ap.ttf
./assets/default/raw/fonts/default_full.ttf
./assets/default/raw/fonts/text.txt
)
